resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [servers:children]
    worker

    [worker:children]
    clickhouse
    vector
    lighthouse

    [clickhouse]
    node01.netology.cloud ansible_host=${yandex_compute_instance.node01.network_interface.0.nat_ip_address}

    [vector]
    node02.netology.cloud ansible_host=${yandex_compute_instance.node02.network_interface.0.nat_ip_address}

    [lighthouse]
    node03.netology.cloud ansible_host=${yandex_compute_instance.node03.network_interface.0.nat_ip_address}

    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.node01,
    yandex_compute_instance.node02,
    yandex_compute_instance.node03
  ]
}