---
- name: clickhouse
  src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.11.0"

- name: vector
  src: git@github.com:gnoy4eg/vector-role.git
  scm: git
  version: "1.0.0"

- name: lighthouse
  src: git@github.com:gnoy4eg/lighthouse-role.git
  scm: git
  version: "1.1.0"

 